// <auto-generated />
namespace MVCPicApp.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AuthenticationFixes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AuthenticationFixes));
        
        string IMigrationMetadata.Id
        {
            get { return "201310200239313_AuthenticationFixes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
