// <auto-generated />
namespace MVCPicApp.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AuditFix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AuditFix));
        
        string IMigrationMetadata.Id
        {
            get { return "201310200259573_AuditFix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
